package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AfstFlotilla generated by hbm2java
 */
@Entity
@Table(name = "afst_flotilla", catalog = "afsinergia")
public class AfstFlotilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8530639024249921895L;
	private Integer idFlotilla;
	private String nombre;
	private AfstContrato afstContrato;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<UnitUnidad> unitUnidads = new HashSet<UnitUnidad>(0);

	public AfstFlotilla() {
	}

	public AfstFlotilla(AfstContrato afstContrato, String nombre) {
		this.afstContrato = afstContrato;
		this.nombre = nombre;
	}

	public AfstFlotilla(String nombre, AfstContrato afstContrato, Date fechaAlta, Date fechaActualiza,
			Date fechaBaja, Set<UnitUnidad> unitUnidads) {
		this.nombre = nombre;
		this.afstContrato = afstContrato;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.unitUnidads = unitUnidads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_flotilla", unique = true, nullable = false)
	public Integer getIdFlotilla() {
		return this.idFlotilla;
	}

	public void setIdFlotilla(Integer idFlotilla) {
		this.idFlotilla = idFlotilla;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_contrato", nullable = false)
	public AfstContrato getAfstContrato() {
		return this.afstContrato;
	}

	public void setAfstContrato(AfstContrato afstContrato) {
		this.afstContrato = afstContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstFlotilla")
	public Set<UnitUnidad> getUnitUnidads() {
		return this.unitUnidads;
	}

	public void setUnitUnidads(Set<UnitUnidad> unitUnidads) {
		this.unitUnidads = unitUnidads;
	}

}
