package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AfstEmpresa generated by hbm2java
 */
@Entity
@Table(name = "afst_empresa", catalog = "afsinergia")
public class AfstEmpresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3090572756048104709L;
	private Integer idEmpresa;
	private String nombre;
	private String direccion;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<AfstGpoemp> afstGpoemps = new HashSet<AfstGpoemp>(0);

	public AfstEmpresa() {
	}

	public AfstEmpresa(String nombre, String direccion, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
	}

	public AfstEmpresa(String nombre, String direccion, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja, Set<AfstGpoemp> afstGpoemps) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.afstGpoemps = afstGpoemps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_empresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "nombre", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", nullable = false, length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", nullable = false, length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstEmpresa")
	public Set<AfstGpoemp> getAfstGpoemps() {
		return this.afstGpoemps;
	}

	public void setAfstGpoemps(Set<AfstGpoemp> afstGpoemps) {
		this.afstGpoemps = afstGpoemps;
	}

}
