package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AfstContrato generated by hbm2java
 */
@Entity
@Table(name = "afst_contrato", catalog = "afsinergia", uniqueConstraints = @UniqueConstraint(columnNames = "no_contrato"))
public class AfstContrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8460508282614491475L;
	private Integer idContrato;
	private AfstCliente afstCliente;
	private String noContrato;
	private String nomContrato;
	private Date inicioContrato;
	private int plazo;
	private int noUnidades;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<AfstFlotilla> afstFlotillas = new HashSet<AfstFlotilla>(0);
	private Set<UsutGpousu> usutGpousus = new HashSet<UsutGpousu>(0);
	private Set<PtlrProdCont> ptlrProdConts = new HashSet<PtlrProdCont>(0);
	private Set<DistDispositivo> distDispositivos = new HashSet<DistDispositivo>(0);

	public AfstContrato() {
	}

	public AfstContrato(AfstCliente afstCliente, String noContrato,
			String nomContrato, Date inicioContrato, int plazo, int noUnidades) {
		this.afstCliente = afstCliente;
		this.noContrato = noContrato;
		this.nomContrato = nomContrato;
		this.inicioContrato = inicioContrato;
		this.plazo = plazo;
		this.noUnidades = noUnidades;
	}

	public AfstContrato(AfstCliente afstCliente, String noContrato,
			String nomContrato, Date inicioContrato, int plazo, int noUnidades,
			Date fechaAlta, Date fechaActualiza, Date fechaBaja,
			Set<AfstFlotilla> afstFlotillas, Set<UsutGpousu> usutGpousus,
			Set<PtlrProdCont> ptlrProdConts,
			Set<DistDispositivo> distDispositivos) {
		this.afstCliente = afstCliente;
		this.noContrato = noContrato;
		this.nomContrato = nomContrato;
		this.inicioContrato = inicioContrato;
		this.plazo = plazo;
		this.noUnidades = noUnidades;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.afstFlotillas = afstFlotillas;
		this.usutGpousus = usutGpousus;
		this.ptlrProdConts = ptlrProdConts;
		this.distDispositivos = distDispositivos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_contrato", unique = true, nullable = false)
	public Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(Integer idContrato) {
		this.idContrato = idContrato;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cliente", nullable = false)
	public AfstCliente getAfstCliente() {
		return this.afstCliente;
	}

	public void setAfstCliente(AfstCliente afstCliente) {
		this.afstCliente = afstCliente;
	}

	@Column(name = "no_contrato", unique = true, nullable = false, length = 45)
	public String getNoContrato() {
		return this.noContrato;
	}

	public void setNoContrato(String noContrato) {
		this.noContrato = noContrato;
	}

	@Column(name = "nom_contrato", nullable = false, length = 45)
	public String getNomContrato() {
		return this.nomContrato;
	}

	public void setNomContrato(String nomContrato) {
		this.nomContrato = nomContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicio_contrato", nullable = false, length = 0)
	public Date getInicioContrato() {
		return this.inicioContrato;
	}

	public void setInicioContrato(Date inicioContrato) {
		this.inicioContrato = inicioContrato;
	}

	@Column(name = "plazo", nullable = false)
	public int getPlazo() {
		return this.plazo;
	}

	public void setPlazo(int plazo) {
		this.plazo = plazo;
	}

	@Column(name = "no_unidades", nullable = false)
	public int getNoUnidades() {
		return this.noUnidades;
	}

	public void setNoUnidades(int noUnidades) {
		this.noUnidades = noUnidades;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstContrato")
	public Set<AfstFlotilla> getAfstFlotillas() {
		return this.afstFlotillas;
	}

	public void setAfstFlotillas(Set<AfstFlotilla> afstFlotillas) {
		this.afstFlotillas = afstFlotillas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstContrato")
	public Set<UsutGpousu> getUsutGpousus() {
		return this.usutGpousus;
	}

	public void setUsutGpousus(Set<UsutGpousu> usutGpousus) {
		this.usutGpousus = usutGpousus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstContrato")
	public Set<PtlrProdCont> getPtlrProdConts() {
		return this.ptlrProdConts;
	}

	public void setPtlrProdConts(Set<PtlrProdCont> ptlrProdConts) {
		this.ptlrProdConts = ptlrProdConts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstContrato")
	public Set<DistDispositivo> getDistDispositivos() {
		return this.distDispositivos;
	}

	public void setDistDispositivos(Set<DistDispositivo> distDispositivos) {
		this.distDispositivos = distDispositivos;
	}

}
