package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AfstGpoemp generated by hbm2java
 */
@Entity
@Table(name = "afst_gpoemp", catalog = "afsinergia", uniqueConstraints = @UniqueConstraint(columnNames = "id_cliente"))
public class AfstGpoemp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5033945709269113499L;
	private Integer idGpoemp;
	private AfstEmpresa afstEmpresa;
	private AfstCliente afstCliente;
	private String nombre;
	private int idEmpp;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<AfstCliente> afstClientes = new HashSet<AfstCliente>(0);

	public AfstGpoemp() {
	}

	public AfstGpoemp(AfstEmpresa afstEmpresa, AfstCliente afstCliente,
			String nombre, int idEmpp) {
		this.afstEmpresa = afstEmpresa;
		this.afstCliente = afstCliente;
		this.nombre = nombre;
		this.idEmpp = idEmpp;
	}

	public AfstGpoemp(AfstEmpresa afstEmpresa, AfstCliente afstCliente,
			String nombre, int idEmpp, Date fechaAlta, Date fechaActualiza,
			Date fechaBaja, Set<AfstCliente> afstClientes) {
		this.afstEmpresa = afstEmpresa;
		this.afstCliente = afstCliente;
		this.nombre = nombre;
		this.idEmpp = idEmpp;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.afstClientes = afstClientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_gpoemp", unique = true, nullable = false)
	public Integer getIdGpoemp() {
		return this.idGpoemp;
	}

	public void setIdGpoemp(Integer idGpoemp) {
		this.idGpoemp = idGpoemp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public AfstEmpresa getAfstEmpresa() {
		return this.afstEmpresa;
	}

	public void setAfstEmpresa(AfstEmpresa afstEmpresa) {
		this.afstEmpresa = afstEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", unique = true, nullable = false)
	public AfstCliente getAfstCliente() {
		return this.afstCliente;
	}

	public void setAfstCliente(AfstCliente afstCliente) {
		this.afstCliente = afstCliente;
	}

	@Column(name = "nombre", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_empp", nullable = false)
	public int getIdEmpp() {
		return this.idEmpp;
	}

	public void setIdEmpp(int idEmpp) {
		this.idEmpp = idEmpp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstGpoemp")
	public Set<AfstCliente> getAfstClientes() {
		return this.afstClientes;
	}

	public void setAfstClientes(Set<AfstCliente> afstClientes) {
		this.afstClientes = afstClientes;
	}

}
