package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AfstCliente generated by hbm2java
 */
@Entity
@Table(name = "afst_cliente", catalog = "afsinergia")
public class AfstCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2831263213724157447L;
	
	private Integer idCliente;
	private AfstGpoemp afstGpoemp;
	private String nombre;
	private String contacto;
	private String telefono;
	private String movil;
	private String mail;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<AfstInstalador> afstInstaladors = new HashSet<AfstInstalador>(0);
	private Set<AfstGpoemp> afstGpoemps = new HashSet<AfstGpoemp>(0);
	private Set<AfstContrato> afstContratos = new HashSet<AfstContrato>(0);

	public AfstCliente() {
	}

	public AfstCliente(AfstGpoemp afstGpoemp, String nombre, String contacto,
			String telefono, String movil, String mail) {
		this.afstGpoemp = afstGpoemp;
		this.nombre = nombre;
		this.contacto = contacto;
		this.telefono = telefono;
		this.movil = movil;
		this.mail = mail;
	}

	public AfstCliente(AfstGpoemp afstGpoemp, String nombre, String contacto,
			String telefono, String movil, String mail, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja,
			Set<AfstInstalador> afstInstaladors,
			Set<AfstGpoemp> afstGpoemps,
			Set<AfstContrato> afstContratos) {
		this.afstGpoemp = afstGpoemp;
		this.nombre = nombre;
		this.contacto = contacto;
		this.telefono = telefono;
		this.movil = movil;
		this.mail = mail;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.afstInstaladors = afstInstaladors;
		this.afstGpoemps = afstGpoemps;
		this.afstContratos = afstContratos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_gpoemp", nullable = false)
	public AfstGpoemp getAfstGpoemp() {
		return this.afstGpoemp;
	}

	public void setAfstGpoemp(AfstGpoemp afstGpoemp) {
		this.afstGpoemp = afstGpoemp;
	}

	@Column(name = "nombre", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "contacto", nullable = false, length = 40)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "movil", nullable = false, length = 15)
	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

	@Column(name = "mail", nullable = false, length = 40)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstCliente")
	public Set<AfstInstalador> getAfstInstaladors() {
		return this.afstInstaladors;
	}

	public void setAfstInstaladors(Set<AfstInstalador> afstInstaladors) {
		this.afstInstaladors = afstInstaladors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstCliente")
	public Set<AfstGpoemp> getAfstGpoemps() {
		return this.afstGpoemps;
	}

	public void setAfstGpoemps(Set<AfstGpoemp> afstGpoemps) {
		this.afstGpoemps = afstGpoemps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afstCliente")
	public Set<AfstContrato> getAfstContratos() {
		return this.afstContratos;
	}

	public void setAfstContratos(Set<AfstContrato> afstContratos) {
		this.afstContratos = afstContratos;
	}

}
