package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DistSim generated by hbm2java
 */
@Entity
@Table(name = "dist_sim", catalog = "afsinergia", uniqueConstraints = {
		@UniqueConstraint(columnNames = "iccid"),
		@UniqueConstraint(columnNames = "linea") })
public class DistSim implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4555042467721495566L;
	private Integer idSim;
	private DistCarrier distCarrier;
	private String iccid;
	private String linea;
	private Date fechaActivacion;
	private Date fechaAlta;
	private Date fechaBaja;
	private Set<DistDispositivo> distDispositivos = new HashSet<DistDispositivo>(
			0);

	public DistSim() {
	}

	public DistSim(DistCarrier distCarrier, String iccid, String linea,
			Date fechaActivacion, Date fechaAlta, Date fechaBaja) {
		this.distCarrier = distCarrier;
		this.iccid = iccid;
		this.linea = linea;
		this.fechaActivacion = fechaActivacion;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
	}

	public DistSim(DistCarrier distCarrier, String iccid, String linea,
			Date fechaActivacion, Date fechaAlta, Date fechaBaja,
			Set<DistDispositivo> distDispositivos) {
		this.distCarrier = distCarrier;
		this.iccid = iccid;
		this.linea = linea;
		this.fechaActivacion = fechaActivacion;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.distDispositivos = distDispositivos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sim", unique = true, nullable = false)
	public Integer getIdSim() {
		return this.idSim;
	}

	public void setIdSim(Integer idSim) {
		this.idSim = idSim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carrier", nullable = false)
	public DistCarrier getDistCarrier() {
		return this.distCarrier;
	}

	public void setDistCarrier(DistCarrier distCarrier) {
		this.distCarrier = distCarrier;
	}

	@Column(name = "iccid", unique = true, nullable = false, length = 20)
	public String getIccid() {
		return this.iccid;
	}

	public void setIccid(String iccid) {
		this.iccid = iccid;
	}

	@Column(name = "linea", unique = true, nullable = false, length = 15)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_activacion", nullable = false, length = 0)
	public Date getFechaActivacion() {
		return this.fechaActivacion;
	}

	public void setFechaActivacion(Date fechaActivacion) {
		this.fechaActivacion = fechaActivacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distSim")
	public Set<DistDispositivo> getDistDispositivos() {
		return this.distDispositivos;
	}

	public void setDistDispositivos(Set<DistDispositivo> distDispositivos) {
		this.distDispositivos = distDispositivos;
	}

}
