package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DistOperador generated by hbm2java
 */
@Entity
@Table(name = "dist_operador", catalog = "afsinergia")
public class DistOperador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4406795468604551341L;
	private Integer idOperador;
	private UnitUnidad unitUnidad;
	private String nombre;
	private String paterno;
	private String materno;
	private Date iniJornada;
	private Date finJornada;
	private Date fechaAlta;
	private Date fehcaActuliza;
	private Date fechaBaja;

	public DistOperador() {
	}

	public DistOperador(UnitUnidad unitUnidad, String nombre, String paterno,
			String materno, Date iniJornada, Date finJornada, Date fechaAlta,
			Date fehcaActuliza, Date fechaBaja) {
		this.unitUnidad = unitUnidad;
		this.nombre = nombre;
		this.paterno = paterno;
		this.materno = materno;
		this.iniJornada = iniJornada;
		this.finJornada = finJornada;
		this.fechaAlta = fechaAlta;
		this.fehcaActuliza = fehcaActuliza;
		this.fechaBaja = fechaBaja;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_operador", unique = true, nullable = false)
	public Integer getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(Integer idOperador) {
		this.idOperador = idOperador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad", nullable = false)
	public UnitUnidad getUnitUnidad() {
		return this.unitUnidad;
	}

	public void setUnitUnidad(UnitUnidad unitUnidad) {
		this.unitUnidad = unitUnidad;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "paterno", nullable = false, length = 45)
	public String getPaterno() {
		return this.paterno;
	}

	public void setPaterno(String paterno) {
		this.paterno = paterno;
	}

	@Column(name = "materno", nullable = false, length = 45)
	public String getMaterno() {
		return this.materno;
	}

	public void setMaterno(String materno) {
		this.materno = materno;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ini_jornada", nullable = false, length = 0)
	public Date getIniJornada() {
		return this.iniJornada;
	}

	public void setIniJornada(Date iniJornada) {
		this.iniJornada = iniJornada;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "fin_jornada", nullable = false, length = 0)
	public Date getFinJornada() {
		return this.finJornada;
	}

	public void setFinJornada(Date finJornada) {
		this.finJornada = finJornada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fehca_actuliza", nullable = false, length = 0)
	public Date getFehcaActuliza() {
		return this.fehcaActuliza;
	}

	public void setFehcaActuliza(Date fehcaActuliza) {
		this.fehcaActuliza = fehcaActuliza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", nullable = false, length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

}
