package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvcFamAccesorio generated by hbm2java
 */
@Entity
@Table(name = "invc_fam_accesorio", catalog = "afsinergia")
public class InvcFamAccesorio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3840729486824260137L;
	private Integer idFamAccesorio;
	private String descripcion;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<InvtAccesorio> invtAccesorios = new HashSet<InvtAccesorio>(0);

	public InvcFamAccesorio() {
	}

	public InvcFamAccesorio(String descripcion, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja) {
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
	}

	public InvcFamAccesorio(String descripcion, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja,
			Set<InvtAccesorio> invtAccesorios) {
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.invtAccesorios = invtAccesorios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_fam_accesorio", unique = true, nullable = false)
	public Integer getIdFamAccesorio() {
		return this.idFamAccesorio;
	}

	public void setIdFamAccesorio(Integer idFamAccesorio) {
		this.idFamAccesorio = idFamAccesorio;
	}

	@Column(name = "descripcion", nullable = false, length = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", nullable = false, length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", nullable = false, length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invcFamAccesorio")
	public Set<InvtAccesorio> getInvtAccesorios() {
		return this.invtAccesorios;
	}

	public void setInvtAccesorios(Set<InvtAccesorio> invtAccesorios) {
		this.invtAccesorios = invtAccesorios;
	}

}
