package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvtAccesorio generated by hbm2java
 */
@Entity
@Table(name = "invt_accesorio", catalog = "afsinergia")
public class InvtAccesorio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4687246907736846774L;
	private Integer idAccesorio;
	private InvcFamAccesorio invcFamAccesorio;
	private DistDispositivo distDispositivo;
	private String nombre;
	private String modelo;
	private String marca;
	private double precioUnidad;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<InvtLote> invtLotes = new HashSet<InvtLote>(0);

	public InvtAccesorio() {
	}

	public InvtAccesorio(InvcFamAccesorio invcFamAccesorio,
			DistDispositivo distDispositivo, String nombre, String modelo,
			String marca, double precioUnidad, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja) {
		this.invcFamAccesorio = invcFamAccesorio;
		this.distDispositivo = distDispositivo;
		this.nombre = nombre;
		this.modelo = modelo;
		this.marca = marca;
		this.precioUnidad = precioUnidad;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
	}

	public InvtAccesorio(InvcFamAccesorio invcFamAccesorio,
			DistDispositivo distDispositivo, String nombre, String modelo,
			String marca, double precioUnidad, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja, Set<InvtLote> invtLotes) {
		this.invcFamAccesorio = invcFamAccesorio;
		this.distDispositivo = distDispositivo;
		this.nombre = nombre;
		this.modelo = modelo;
		this.marca = marca;
		this.precioUnidad = precioUnidad;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.invtLotes = invtLotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_accesorio", unique = true, nullable = false)
	public Integer getIdAccesorio() {
		return this.idAccesorio;
	}

	public void setIdAccesorio(Integer idAccesorio) {
		this.idAccesorio = idAccesorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fam_accesorio", nullable = false)
	public InvcFamAccesorio getInvcFamAccesorio() {
		return this.invcFamAccesorio;
	}

	public void setInvcFamAccesorio(InvcFamAccesorio invcFamAccesorio) {
		this.invcFamAccesorio = invcFamAccesorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dispositivo", nullable = false)
	public DistDispositivo getDistDispositivo() {
		return this.distDispositivo;
	}

	public void setDistDispositivo(DistDispositivo distDispositivo) {
		this.distDispositivo = distDispositivo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "modelo", nullable = false, length = 45)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "marca", nullable = false, length = 45)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "precio_unidad", nullable = false, precision = 22, scale = 0)
	public double getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(double precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", nullable = false, length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", nullable = false, length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invtAccesorio")
	public Set<InvtLote> getInvtLotes() {
		return this.invtLotes;
	}

	public void setInvtLotes(Set<InvtLote> invtLotes) {
		this.invtLotes = invtLotes;
	}

}
