package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * InvtLote generated by hbm2java
 */
@Entity
@Table(name = "invt_lote", catalog = "afsinergia", uniqueConstraints = @UniqueConstraint(columnNames = "num_factura"))
public class InvtLote implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5828590035175008267L;
	private Integer idLote;
	private InvtAccesorio invtAccesorio;
	private int cantProd;
	private String numFactura;
	private Date fechaPedido;
	private Date fechaEntrega;

	public InvtLote() {
	}

	public InvtLote(InvtAccesorio invtAccesorio, int cantProd,
			String numFactura, Date fechaPedido, Date fechaEntrega) {
		this.invtAccesorio = invtAccesorio;
		this.cantProd = cantProd;
		this.numFactura = numFactura;
		this.fechaPedido = fechaPedido;
		this.fechaEntrega = fechaEntrega;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_lote", unique = true, nullable = false)
	public Integer getIdLote() {
		return this.idLote;
	}

	public void setIdLote(Integer idLote) {
		this.idLote = idLote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_accesorio", nullable = false)
	public InvtAccesorio getInvtAccesorio() {
		return this.invtAccesorio;
	}

	public void setInvtAccesorio(InvtAccesorio invtAccesorio) {
		this.invtAccesorio = invtAccesorio;
	}

	@Column(name = "cant_prod", nullable = false)
	public int getCantProd() {
		return this.cantProd;
	}

	public void setCantProd(int cantProd) {
		this.cantProd = cantProd;
	}

	@Column(name = "num_factura", unique = true, nullable = false, length = 15)
	public String getNumFactura() {
		return this.numFactura;
	}

	public void setNumFactura(String numFactura) {
		this.numFactura = numFactura;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_pedido", nullable = false, length = 0)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_entrega", nullable = false, length = 0)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

}
