package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PtlcProducto generated by hbm2java
 */
@Entity
@Table(name = "ptlc_producto", catalog = "afsinergia")
public class PtlcProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6119223377693293589L;
	private Integer idProd;
	private String nombre;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<PtlrProdCont> ptlrProdConts = new HashSet<PtlrProdCont>(0);
	private Set<PtlcModulo> ptlcModulos = new HashSet<PtlcModulo>(0);

	public PtlcProducto() {
	}

	public PtlcProducto(String nombre) {
		this.nombre = nombre;
	}

	public PtlcProducto(String nombre, Date fechaAlta, Date fechaActualiza,
			Date fechaBaja, Set<PtlrProdCont> ptlrProdConts,
			Set<PtlcModulo> ptlcModulos) {
		this.nombre = nombre;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.ptlrProdConts = ptlrProdConts;
		this.ptlcModulos = ptlcModulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_prod", unique = true, nullable = false)
	public Integer getIdProd() {
		return this.idProd;
	}

	public void setIdProd(Integer idProd) {
		this.idProd = idProd;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ptlcProducto")
	public Set<PtlrProdCont> getPtlrProdConts() {
		return this.ptlrProdConts;
	}

	public void setPtlrProdConts(Set<PtlrProdCont> ptlrProdConts) {
		this.ptlrProdConts = ptlrProdConts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ptlcProducto")
	public Set<PtlcModulo> getPtlcModulos() {
		return this.ptlcModulos;
	}

	public void setPtlcModulos(Set<PtlcModulo> ptlcModulos) {
		this.ptlcModulos = ptlcModulos;
	}

}
