package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PtlcFuncion generated by hbm2java
 */
@Entity
@Table(name = "ptlc_funcion", catalog = "afsinergia", uniqueConstraints = @UniqueConstraint(columnNames = "url_controlador"))
public class PtlcFuncion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5269547466206831343L;
	private Integer idFun;
	private PtlcModulo ptlcModulo;
	private String nomFun;
	private String tipo;
	private String urlControlador;
	private String icono;
	private Set<PtltPrivilegio> ptltPrivilegios = new HashSet<PtltPrivilegio>(0);

	public PtlcFuncion() {
	}

	public PtlcFuncion(PtlcModulo ptlcModulo, String nomFun, String tipo,
			String urlControlador, String icono) {
		this.ptlcModulo = ptlcModulo;
		this.nomFun = nomFun;
		this.tipo = tipo;
		this.urlControlador = urlControlador;
		this.icono = icono;
	}

	public PtlcFuncion(PtlcModulo ptlcModulo, String nomFun, String tipo,
			String urlControlador, String icono, Set<PtltPrivilegio> ptltPrivilegios) {
		this.ptlcModulo = ptlcModulo;
		this.nomFun = nomFun;
		this.tipo = tipo;
		this.urlControlador = urlControlador;
		this.ptltPrivilegios = ptltPrivilegios;
		this.icono = icono;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_fun", unique = true, nullable = false)
	public Integer getIdFun() {
		return this.idFun;
	}

	public void setIdFun(Integer idFun) {
		this.idFun = idFun;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modulo", nullable = false)
	public PtlcModulo getPtlcModulo() {
		return this.ptlcModulo;
	}

	public void setPtlcModulo(PtlcModulo ptlcModulo) {
		this.ptlcModulo = ptlcModulo;
	}

	@Column(name = "nom_fun", nullable = false, length = 30)
	public String getNomFun() {
		return this.nomFun;
	}

	public void setNomFun(String nomFun) {
		this.nomFun = nomFun;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "url_controlador", unique = true, nullable = false, length = 100)
	public String getUrlControlador() {
		return this.urlControlador;
	}

	public void setUrlControlador(String urlControlador) {
		this.urlControlador = urlControlador;
	}

	@Column(name = "icono", length = 45)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ptlcFuncion")
	public Set<PtltPrivilegio> getPtltPrivilegios() {
		return this.ptltPrivilegios;
	}

	public void setPtltPrivilegios(Set<PtltPrivilegio> ptltPrivilegios) {
		this.ptltPrivilegios = ptltPrivilegios;
	}
}
