package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PtlrProdCont generated by hbm2java
 */
@Entity
@Table(name = "ptlr_prod_cont", catalog = "afsinergia")
public class PtlrProdCont implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6482992044498489224L;
	private PtlrProdContId id;
	private PtlcProducto ptlcProducto;
	private AfstContrato afstContrato;
	private Date fechaAlta;
	private Date fechaBaja;
	private Date vigencia;

	public PtlrProdCont() {
	}

	public PtlrProdCont(PtlrProdContId id, PtlcProducto ptlcProducto,
			AfstContrato afstContrato, Date fechaAlta, Date fechaBaja,
			Date vigencia) {
		this.id = id;
		this.ptlcProducto = ptlcProducto;
		this.afstContrato = afstContrato;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.vigencia = vigencia;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProd", column = @Column(name = "id_prod", nullable = false)),
			@AttributeOverride(name = "idContrato", column = @Column(name = "id_contrato", nullable = false)) })
	public PtlrProdContId getId() {
		return this.id;
	}

	public void setId(PtlrProdContId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prod", nullable = false, insertable = false, updatable = false)
	public PtlcProducto getPtlcProducto() {
		return this.ptlcProducto;
	}

	public void setPtlcProducto(PtlcProducto ptlcProducto) {
		this.ptlcProducto = ptlcProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contrato", nullable = false, insertable = false, updatable = false)
	public AfstContrato getAfstContrato() {
		return this.afstContrato;
	}

	public void setAfstContrato(AfstContrato afstContrato) {
		this.afstContrato = afstContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", nullable = false, length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vigencia", nullable = false, length = 0)
	public Date getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Date vigencia) {
		this.vigencia = vigencia;
	}

}
