package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PtlrProdContId generated by hbm2java
 */
@Embeddable
public class PtlrProdContId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8746471984199373550L;
	private int idProd;
	private int idContrato;

	public PtlrProdContId() {
	}

	public PtlrProdContId(int idProd, int idContrato) {
		this.idProd = idProd;
		this.idContrato = idContrato;
	}

	@Column(name = "id_prod", nullable = false)
	public int getIdProd() {
		return this.idProd;
	}

	public void setIdProd(int idProd) {
		this.idProd = idProd;
	}

	@Column(name = "id_contrato", nullable = false)
	public int getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(int idContrato) {
		this.idContrato = idContrato;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PtlrProdContId))
			return false;
		PtlrProdContId castOther = (PtlrProdContId) other;

		return (this.getIdProd() == castOther.getIdProd())
				&& (this.getIdContrato() == castOther.getIdContrato());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProd();
		result = 37 * result + this.getIdContrato();
		return result;
	}

}
