package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PtltPrivilegio generated by hbm2java
 */
@Entity
@Table(name = "ptlt_privilegio", catalog = "afsinergia")
public class PtltPrivilegio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4276613371108652726L;
	
	private int idPrivilegio;
	private PtlcFuncion ptlcFuncion;
	private UsutGpousu usutGpousu;
	private PtlcModulo ptlcModulo;

	public PtltPrivilegio() {
	}

	public PtltPrivilegio(int idPrivilegio, PtlcFuncion ptlcFuncion,
			UsutGpousu usutGpousu, PtlcModulo ptlcModulo) {
		this.idPrivilegio = idPrivilegio;
		this.ptlcFuncion = ptlcFuncion;
		this.usutGpousu = usutGpousu;
		this.ptlcModulo = ptlcModulo;
	}

	@Id
	@Column(name = "id_privilegio", unique = true, nullable = false)
	public int getIdPrivilegio() {
		return this.idPrivilegio;
	}

	public void setIdPrivilegio(int idPrivilegio) {
		this.idPrivilegio = idPrivilegio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fun", nullable = false)
	public PtlcFuncion getPtlcFuncion() {
		return this.ptlcFuncion;
	}

	public void setPtlcFuncion(PtlcFuncion ptlcFuncion) {
		this.ptlcFuncion = ptlcFuncion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_gpousu", nullable = false)
	public UsutGpousu getUsutGpousu() {
		return this.usutGpousu;
	}

	public void setUsutGpousu(UsutGpousu usutGpousu) {
		this.usutGpousu = usutGpousu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modulo", nullable = false)
	public PtlcModulo getPtlcModulo() {
		return this.ptlcModulo;
	}

	public void setPtlcModulo(PtlcModulo ptlcModulo) {
		this.ptlcModulo = ptlcModulo;
	}

}
