package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnicTipoUnidad generated by hbm2java
 */
@Entity
@Table(name = "unic_tipo_unidad", catalog = "afsinergia")
public class UnicTipoUnidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6377096367148738516L;
	private Integer idTipoUnidad;
	private String nomUnidad;
	private Set<UnitUnidad> unitUnidads = new HashSet<UnitUnidad>(0);

	public UnicTipoUnidad() {
	}

	public UnicTipoUnidad(String nomUnidad) {
		this.nomUnidad = nomUnidad;
	}

	public UnicTipoUnidad(String nomUnidad, Set<UnitUnidad> unitUnidads) {
		this.nomUnidad = nomUnidad;
		this.unitUnidads = unitUnidads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tipo_unidad", unique = true, nullable = false)
	public Integer getIdTipoUnidad() {
		return this.idTipoUnidad;
	}

	public void setIdTipoUnidad(Integer idTipoUnidad) {
		this.idTipoUnidad = idTipoUnidad;
	}

	@Column(name = "nom_unidad", nullable = false, length = 45)
	public String getNomUnidad() {
		return this.nomUnidad;
	}

	public void setNomUnidad(String nomUnidad) {
		this.nomUnidad = nomUnidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unicTipoUnidad")
	public Set<UnitUnidad> getUnitUnidads() {
		return this.unitUnidads;
	}

	public void setUnitUnidads(Set<UnitUnidad> unitUnidads) {
		this.unitUnidads = unitUnidads;
	}

}
