package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UnitUnidad generated by hbm2java
 */
@Entity
@Table(name = "unit_unidad", catalog = "afsinergia", uniqueConstraints = @UniqueConstraint(columnNames = "id_dispositivo"))
public class UnitUnidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1628114684929951312L;
	private Integer idUnidad;
	private UnicTipoUnidad unicTipoUnidad;
	private DistDispositivo distDispositivo;
	private AfstFlotilla afstFlotilla;
	private String nombre;
	private String foto;
	private String placas;
	private String motor;
	private String color;
	private String modelo;
	private Integer noPuertas;
	private String anio;
	private String marca;
	private Double capCombustible;
	private String fotoTCirculacion;
	private Integer ondometro;
	private Double capCarga;
	private String noPoliza;
	private Date venPoliza;
	private Boolean genero;
	private String carEspecial;
	private Date fechaNacimiento;
	private String proporcion;
	private String tecnologiaCel;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<DistOperador> distOperadors = new HashSet<DistOperador>(0);

	public UnitUnidad() {
	}

	public UnitUnidad(UnicTipoUnidad unicTipoUnidad,
			DistDispositivo distDispositivo, AfstFlotilla afstFlotilla,
			String nombre,
			String foto, Date fechaAlta, Date fechaActualiza, Date fechaBaja) {
		this.unicTipoUnidad = unicTipoUnidad;
		this.distDispositivo = distDispositivo;
		this.afstFlotilla = afstFlotilla;
		this.nombre = nombre;
		this.foto = foto;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
	}

	public UnitUnidad(UnicTipoUnidad unicTipoUnidad,
			DistDispositivo distDispositivo, AfstFlotilla afstFlotilla,
			String nombre,
			String foto, String placas, String motor, String color,
			String modelo, Integer noPuertas, String anio, String marca,
			Double capCombustible, String fotoTCirculacion, Integer ondometro,
			Double capCarga, String noPoliza, Date venPoliza, Boolean genero,
			String carEspecial, Date fechaNacimiento, String proporcion,
			String tecnologiaCel, Date fechaAlta, Date fechaActualiza,
			Date fechaBaja, Set<DistOperador> distOperadors) {
		this.unicTipoUnidad = unicTipoUnidad;
		this.distDispositivo = distDispositivo;
		this.afstFlotilla = afstFlotilla;
		this.nombre = nombre;
		this.foto = foto;
		this.placas = placas;
		this.motor = motor;
		this.color = color;
		this.modelo = modelo;
		this.noPuertas = noPuertas;
		this.anio = anio;
		this.marca = marca;
		this.capCombustible = capCombustible;
		this.fotoTCirculacion = fotoTCirculacion;
		this.ondometro = ondometro;
		this.capCarga = capCarga;
		this.noPoliza = noPoliza;
		this.venPoliza = venPoliza;
		this.genero = genero;
		this.carEspecial = carEspecial;
		this.fechaNacimiento = fechaNacimiento;
		this.proporcion = proporcion;
		this.tecnologiaCel = tecnologiaCel;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.distOperadors = distOperadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_unidad", unique = true, nullable = false)
	public Integer getIdUnidad() {
		return this.idUnidad;
	}

	public void setIdUnidad(Integer idUnidad) {
		this.idUnidad = idUnidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tipo_unidad", nullable = false)
	public UnicTipoUnidad getUnicTipoUnidad() {
		return this.unicTipoUnidad;
	}

	public void setUnicTipoUnidad(UnicTipoUnidad unicTipoUnidad) {
		this.unicTipoUnidad = unicTipoUnidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dispositivo", unique = true, nullable = false)
	public DistDispositivo getDistDispositivo() {
		return this.distDispositivo;
	}

	public void setDistDispositivo(DistDispositivo distDispositivo) {
		this.distDispositivo = distDispositivo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_flotilla", nullable = false)
	public AfstFlotilla getAfstFlotilla() {
		return this.afstFlotilla;
	}

	public void setAfstFlotilla(AfstFlotilla afstFlotilla) {
		this.afstFlotilla = afstFlotilla;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "foto", length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "placas", length = 20)
	public String getPlacas() {
		return this.placas;
	}

	public void setPlacas(String placas) {
		this.placas = placas;
	}

	@Column(name = "motor", length = 30)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "color", length = 30)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "modelo", length = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "no_puertas")
	public Integer getNoPuertas() {
		return this.noPuertas;
	}

	public void setNoPuertas(Integer noPuertas) {
		this.noPuertas = noPuertas;
	}

	@Column(name = "anio", length = 4)
	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	@Column(name = "marca", length = 45)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "cap_combustible", precision = 22, scale = 0)
	public Double getCapCombustible() {
		return this.capCombustible;
	}

	public void setCapCombustible(Double capCombustible) {
		this.capCombustible = capCombustible;
	}

	@Column(name = "foto_t_circulacion", length = 100)
	public String getFotoTCirculacion() {
		return this.fotoTCirculacion;
	}

	public void setFotoTCirculacion(String fotoTCirculacion) {
		this.fotoTCirculacion = fotoTCirculacion;
	}

	@Column(name = "ondometro")
	public Integer getOndometro() {
		return this.ondometro;
	}

	public void setOndometro(Integer ondometro) {
		this.ondometro = ondometro;
	}

	@Column(name = "cap_carga", precision = 22, scale = 0)
	public Double getCapCarga() {
		return this.capCarga;
	}

	public void setCapCarga(Double capCarga) {
		this.capCarga = capCarga;
	}

	@Column(name = "no_poliza", length = 20)
	public String getNoPoliza() {
		return this.noPoliza;
	}

	public void setNoPoliza(String noPoliza) {
		this.noPoliza = noPoliza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ven_poliza", length = 0)
	public Date getVenPoliza() {
		return this.venPoliza;
	}

	public void setVenPoliza(Date venPoliza) {
		this.venPoliza = venPoliza;
	}

	@Column(name = "genero")
	public Boolean getGenero() {
		return this.genero;
	}

	public void setGenero(Boolean genero) {
		this.genero = genero;
	}

	@Column(name = "car_especial", length = 45)
	public String getCarEspecial() {
		return this.carEspecial;
	}

	public void setCarEspecial(String carEspecial) {
		this.carEspecial = carEspecial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 0)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "proporcion", length = 45)
	public String getProporcion() {
		return this.proporcion;
	}

	public void setProporcion(String proporcion) {
		this.proporcion = proporcion;
	}

	@Column(name = "tecnologia_cel", length = 45)
	public String getTecnologiaCel() {
		return this.tecnologiaCel;
	}

	public void setTecnologiaCel(String tecnologiaCel) {
		this.tecnologiaCel = tecnologiaCel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", nullable = false, length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitUnidad")
	public Set<DistOperador> getDistOperadors() {
		return this.distOperadors;
	}

	public void setDistOperadors(Set<DistOperador> distOperadors) {
		this.distOperadors = distOperadors;
	}

	@Override
	public String toString() {
		return "UnitUnidad [idUnidad=" + idUnidad + ", unicTipoUnidad="
				+ unicTipoUnidad + ", distDispositivo=" + distDispositivo
				+ ", afstFlotilla=" + afstFlotilla + ", nombre=" + nombre + ", foto=" + foto
				+ ", placas=" + placas + ", motor=" + motor + ", color="
				+ color + ", modelo=" + modelo + ", noPuertas=" + noPuertas
				+ ", anio=" + anio + ", marca=" + marca + ", capCombustible="
				+ capCombustible + ", fotoTCirculacion=" + fotoTCirculacion
				+ ", ondometro=" + ondometro + ", capCarga=" + capCarga
				+ ", noPoliza=" + noPoliza + ", venPoliza=" + venPoliza
				+ ", genero=" + genero + ", carEspecial=" + carEspecial
				+ ", fechaNacimiento=" + fechaNacimiento + ", proporcion="
				+ proporcion + ", tecnologiaCel=" + tecnologiaCel
				+ ", fechaAlta=" + fechaAlta + ", fechaActualiza="
				+ fechaActualiza + ", fechaBaja=" + fechaBaja
				+ ", distOperadors=" + distOperadors + "]";
	}

}
