package com.afsinergia.org.model;

// Generated 15/08/2014 02:52:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsutGpousu generated by hbm2java
 */
@Entity
@Table(name = "usut_gpousu", catalog = "afsinergia")
public class UsutGpousu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7775192660596383176L;
	private Integer idGpousu;
	private AfstContrato afstContrato;
	private String nombre;
	private Date fechaAlta;
	private Date fechaActualiza;
	private Date fechaBaja;
	private Set<PtltPrivilegio> ptltPrivilegios = new HashSet<PtltPrivilegio>(0);
	private Set<UsutUsuario> usutUsuarios = new HashSet<UsutUsuario>(0);

	public UsutGpousu() {
	}

	public UsutGpousu(AfstContrato afstContrato, String nombre) {
		this.afstContrato = afstContrato;
		this.nombre = nombre;
	}

	public UsutGpousu(AfstContrato afstContrato, String nombre, Date fechaAlta,
			Date fechaActualiza, Date fechaBaja,
			Set<PtltPrivilegio> ptltPrivilegios, Set<UsutUsuario> usutUsuarios) {
		this.afstContrato = afstContrato;
		this.nombre = nombre;
		this.fechaAlta = fechaAlta;
		this.fechaActualiza = fechaActualiza;
		this.fechaBaja = fechaBaja;
		this.ptltPrivilegios = ptltPrivilegios;
		this.usutUsuarios = usutUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_gpousu", unique = true, nullable = false)
	public Integer getIdGpousu() {
		return this.idGpousu;
	}

	public void setIdGpousu(Integer idGpousu) {
		this.idGpousu = idGpousu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_contrato", nullable = false)
	public AfstContrato getAfstContrato() {
		return this.afstContrato;
	}

	public void setAfstContrato(AfstContrato afstContrato) {
		this.afstContrato = afstContrato;
	}

	@Column(name = "nombre", nullable = false, length = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 0)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_actualiza", length = 0)
	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 0)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usutGpousu")
	public Set<PtltPrivilegio> getPtltPrivilegios() {
		return this.ptltPrivilegios;
	}

	public void setPtltPrivilegios(Set<PtltPrivilegio> ptltPrivilegios) {
		this.ptltPrivilegios = ptltPrivilegios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usutGpousu")
	public Set<UsutUsuario> getUsutUsuarios() {
		return this.usutUsuarios;
	}

	public void setUsutUsuarios(Set<UsutUsuario> usutUsuarios) {
		this.usutUsuarios = usutUsuarios;
	}

}
