package com.afsinergia.org.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * UsutUsuario generated by hbm2java
 */
@Entity
@Table(name = "usut_rol", catalog = "afsinergia")
public class UsutRol {
	private int idRol;
	private String nomRol;
	private List<UsutUsuario> usutUsuarios;
	
	public UsutRol(){}

	public UsutRol(int idRol, String nomRol, List<UsutUsuario> usutUsuarios) {
		super();
		this.idRol = idRol;
		this.nomRol = nomRol;
		this.usutUsuarios = usutUsuarios;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nom_rol", nullable = false, length = 20)
	public String getNomRol() {
		return nomRol;
	}

	public void setNomRol(String nomRol) {
		this.nomRol = nomRol;
	}
	
	@ManyToMany(mappedBy = "roles")
	public List<UsutUsuario> getusutUsuarios() {
		return usutUsuarios;
	}

	public void setusutUsuarios(List<UsutUsuario> usutUsuarios) {
		this.usutUsuarios = usutUsuarios;
	}
	
}
